services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "8080:8080"
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: "1.21.1"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./_data/mc-data:/data